### ISSUE TITLE
comment indentation?

### ISSUE THREAD

**Issue by houndofsound** [ocaml/tuareg#213] opened 2019-07-02 20:45 UTC
I haven't found any customisation of comment indentation and
the default looks broken:

```
(* start something here...
 then C-j goes 1 space in...
 dadada
 *) 
```

other peoples code comments make me envious:
```
(*   start
     continue...
     more ...
*)
```
what can I do about this? (the indentation, not the envy!)

**Comment by gadmm** [comment] 2020-05-15 13:07
The behaviour differs if I use Tab or M-q. With M-q I get the following:
```ocaml
(** aaa
   bbb
   ccc
   *)
```
(assuming the `ccc` line is long enough). Whereas with Tab I get:
```ocaml
(** aaa
    bbb
    ccc
*)
```
It would be nice if the behaviours match. (The latter looks better IMO.) Is there something to do about it?

**Comment by gabrielhdt** [comment] 2020-05-22 10:10
Hi, I implemented exactly what @gadmm suggested in his post, that is, the indent of the `fill-comment` is equal to the number of stars plus two (that is, if you open your comment with `(**`, you have an indentation of four; with `(*`: of three).

It does not solve the initial wish though. Implementation wise, in the PR, the cursor is moved to the end of the comment opener (to the end of regexp `(\*+`). But we can also move the cursor to the first non blank and non asterisk character which would, it seems, answer @houndofsound's request.

**Comment by mattiase** [comment] 2021-08-29 11:05
There seems to be several interlinked problems:
1. Reformatting a comment with `M-q` should use a continuation indentation that is consistent with the start of the comment, `(*` vs `(**` or text on the previous non-blank line inside the comment.
2. `M-q` should only affect a single paragraph in the comment. Currently, all paragraphs are reformatted which destroys careful manual formatting.
3. Pressing return in a comment with the `electric-indent` minor mode enabled (which it is by default) should automatically indent the new line according to the previous line. This is how electric-indent is supposed to work, what a user expects, and the most convenient behaviour for programming.

For problem 1, using the length of the initial `(\*+` is inadequate: someone starting a comment with `(**************` is more likely to want an initial line of asterisks than everything indented 16 spaces. Just recognising `(**` as a special case is probably enough.

Problem 3 is caused by `smie-setup` setting `indent-line-function` to `smie-indent-line` which just returns `noindent` inside a comment. That will have to be worked around (unless @monnier thinks it should be done inside SMIE). Something like
```
  (let ((act (smie-indent-line)))
    (if (eq act 'noindent)
        (indent--default-inside-comment)
      act)))
```
would do, except that it's not wonderful to call an internal function like that so we may end up copying the code instead.

Also, what should the indentation be after the user presses return immediately after `(*`?
Should `comment-continue` be respected in that case, or in any other case?

**Comment by mattiase** [comment] 2021-09-02 15:06
PR #271 should fix the inadequacies listed so far and adds more features: @-tags now get special treatment inside doc comments as paragraph breaks on their own. It uses the indentation
```
  @param first line
         more
         lines
```
– ie, subsequent lines indented to the text following the tag. It looks neat but means that `@param` text is indented 7 spaces, `@see` text 5 spaces and so on. An alternative would be to pick a fixed indentation (2 spaces, say):
```
  @param first line
    more
    lines
````

**Comment by Chris00** [comment] 2021-09-02 17:48
I personally prefer the second solution (less indentation, more uniform).

**Comment by mattiase** [comment] 2021-09-02 20:00
Either is fine with me! I've pushed a change to PR #271. You could test them both to see which one you like better.

**Comment by mattiase** [comment] 2022-01-04 17:29
As a small reminder, PR #271 that fixes this issue is ready for merging.

**Closed** 2022-01-04 20:40 UTC
